FROM node:lts-alpine AS build-state 
WORKDIR /app
RUN npm init -y && npm install json-server
WORKDIR /app/data
COPY ./data/db.json ./db.json 
VOLUME /app/data
CMD [ "npx", "json-server", "--watch", "./data/db.json", "--port", "5001" ]
EXPOSE 5001